### ISSUE TITLE
Current version triggers no matching package found error

### ISSUE THREAD

**Issue by juanantoniodelgado** [endroid/installer#1]
Hi!

I was updating my project current dependencies and I've found that the new version triggers this error. Any ideas of what may be failing?

endroid/installer 1.0.4 requires composer-plugin-api ^1.1 -> no matching package found.

Complete log track:
Installation request for endroid/installer 1.0.4 -> satisfiable by endroid/installer[1.0.4]. - endroid/installer 1.0.4 requires composer-plugin-api ^1.1 -> no matching package found. Problem 2 - endroid/installer 1.0.4 requires composer-plugin-api ^1.1 -> no matching package found. - endroid/qr-code 3.2.12 requires endroid/installer ^1.0.3 -> satisfiable by endroid/installer[1.0.4]. - Installation request for endroid/qr-code 3.2.12 -> satisfiable by endroid/qr-code[3.2.12]. Potential causes: - A typo in the package name - The package is not available in a stable-enough version according to your minimum-stability setting

**Comment by endroid** [comment]
Hoi @juanantoniodelgado looks like you are using an old version of composer. Please update composer and let me know if that helped. You can use composer self-update to update to the lastest version.
