### ISSUE TITLE
A bit more documentation for developers

### ISSUE THREAD

**Issue by tacman** [endroid/installer#11]
This looks great, and will solve the problems you describe in your blog post.  

I want to make sure I understand what I need to do to use this with my own bundles.  

> Add the configuration files you want to be copied upon installation.

Can we expand on this a bit?  For example

---

At the root level of your Symfony bundle, add the directory .install/symfony.  Under that, add the files you want copied, such as config/packages/your_bundle.yaml.

From your bundle, run

```bash
composer req endroid/installer
composer config allow-plugins.endroid/installer true
```

This modifies the composer.json file so that applications that require your bundle with automatically copies the files in .install/symfony, without submitting a recipe.  

---

Question: does (or could) installer do anything else, like insert code into another file, like recipes does?  Typically those are environment variable, but in my case, when the developer installs my bundle, I want it to add a line that dump the fos routes.  This would be a bonus, 99% of the time I just want to copy files, as you support.

Another question: is there a way to re-install?  If so, can you document that in the readme?  As a developer, I frequently want to test the install.

I can make a PR to the readme if the above is correct, or you can take this and do that, along with anything else I've missed.  I can't wait to start using this!

**Comment by endroid** [comment]
The installer only copies files. And it should only install the configuration once, as user made modifications should never be overwritten. I think this is currently covered by a file exists check.

I will update the readme to include some more information like this.
