### ISSUE TITLE
[Feature Request] Follow up messages

### ISSUE THREAD

**Issue by tacman** [endroid/installer#12]
In a symfony recipe, there's a key for post-install text, that often displays what the next steps are.  

That would be nice to have here, especially to prompt the developer of available console commands.

**Comment by tacman** [comment]
I'm going to work on this and also adding keys to .env, like the Symfony recipes do.  Any guidance before I start?

**Comment by tacman** [comment]
Any suggestions for how to test this?  In particular, it works the first time I install it, but when I run the recipe install a second time (with --force), it seems to skip the install.  

Do I need to listen for a particular event?    I've tried this, but nothing is firing after the initial install.

```php
    public static function getSubscribedEvents(): array
    {
        return [
            ScriptEvents::PRE_UPDATE_CMD => ['install', 1],
            ScriptEvents::PRE_INSTALL_CMD => ['install', 1],
            ScriptEvents::POST_INSTALL_CMD => ['install', 1],
            ScriptEvents::POST_UPDATE_CMD => ['install', 1],
        ];
    }
```

**Comment by endroid** [comment]
Hi @tacman I'm not sure if I need / will add functionality like this in my library as I want to keep it as small as possible. What is your reason for not using Symfony Flex if you need all this?

**Comment by tacman** [comment]
Flex is pretty awkward to use, and needs manual approval.  The CI throws errors if your bundle doesn't support PHP 7.

The endroid installer has been working out great for me, and I think it could encompass more.  Of course, I'm trying to work within the flex recipes-contrib repo, but it seems so much more natural to have the bundle recipe with the bundle itself.  

Adding post-install.txt and .env and .gitignore don't seem too hard and would add the important missing steps for me.  My challenge now is how to test this plugin (even if I only end up using my fork).

**Comment by endroid** [comment]
I understand, those were also the main reasons for me to switch to a custom solution. I think you can test your composer plugin by creating a dummy project and adding the repository via "repositories" with type "path" in your composer.json. That way you can point to the location of your fork while you are developing in it and install / update in the dummy project to test it. Good luck!

**Comment by tacman** [comment]
Indeed, that's what I've been doing.  And it works great the first time.  But then when I run 

```bash
composer config allow-plugins.endroid/installer true
composer config repositories.tacman_installer '{"type": "path", "url": "/home/tac/g/tacman/installer"}' 
composer require endroid/installer:*@dev
```

```bash
# works fine the first time
composer recipes:install survos/my-bundle
# activate() is called, but not install, maybe listening for the wrong events?
composer recipes:install --force survos/my-bundle
```

the install method isn't called.

**Comment by endroid** [comment]
Maybe it does not trigger when you have the deps already installed and specifically the lock file is unchanged. What if you try to install an additional library as an extra argument the second time?

**Comment by tacman** [comment]
that didn't work.  I've also removed symfony.lock and a few other things like that.  My current hack is to simple call install() during activate (while developing)

BUT that leads me to the next step, which is how to configure this.  I'd like to mimic the Flex recipes as much as possible (e.g. a manifest.json file), so that someday the plugin could support publishing the recipe to flex.  That is, during development use the endroid installer, then copy the .install directory (modified to flex rules) to the recipe-contrib directory and then submit a PR for that.

**Comment by endroid** [comment]
Haha, great idea but really to big for this repo, I really only want a simple copy. I now see you are performing a recipes:install but that does not trigger a composer install event I think. Have you tried `composer install`? Also a composer require should work (first time with the plugin, consecutive call a different package so the lock file changes).

**Comment by tacman** [comment]
Thanks -- using composer require does trigger the plugin.

Yeah, I realize my changes might not be a good fit for this repo, but it's a great starting point and useful for most many projects.  

I ran across https://packagist.org/packages/aih/aih-bundle yesterday, and thought about the installation instructions.  Rather than go through the pain of contributing a recipe, he provided instructions for copying from the repo.  I think he just wasn't aware of your installer, since that would make so much sense.

![image](https://github.com/user-attachments/assets/95d7a3ab-32f0-45f7-8bfd-9c0e99f3c5f7)


Except for the .env, which I'm working on!

**Comment by tacman** [comment]
OK, although you said it's probably not a good fit for this plugin, I'd love your feedback on what structure to use.

I'm developing using this structure;

![image](https://github.com/user-attachments/assets/a8a8b027-ada8-4761-80a5-717927bffb66)

where the .txt files have special meanings.  I may also add manifest.json support.

Where would you suggest I put the environment variables to be inserted into .env?  That's my top issue now.

**Comment by tacman** [comment]
My fork now supports .env, .gitignore and post-install instructions.  It doesn't feel elegant, but I think it will work for my purposes. 

Thoughts on a PR?  Or should I just use my fork?

**Comment by tacman** [comment]
Do you know how to tell from within the Installer class if the package has been installed in symfony.lock?

**Comment by endroid** [comment]
You could parse that but I think that is really Flex specific

**Comment by tacman** [comment]
I now check if the package is installed in symfony.lock.  

It's a bit of a hack, but appears to do what I want, adding lines to .env and .gitignore, and displaying some notes.  ping me if you're open to a PR
