### ISSUE TITLE
Add link to sample projects that use this.

### ISSUE THREAD

**Issue by tacman** [endroid/installer#14]
Can you add some links to bundles / packages that use this, to see it in action?  Right now I'm just using it for creating /config/packages and config/routes, but if there's more that can happen I'd like to see examples.  Thx.

**Comment by endroid** [comment]
Hi @tacman you can find the dependent repositories on Packagist https://packagist.org/packages/endroid/installer/dependents?order_by=downloads&requires=all.

**Comment by tacman** [comment]
Thanks!  OK if I add that link to the README?

**Comment by endroid** [comment]
Not necessary, thank you.
