### ISSUE TITLE
Warning "Endroid Installer did not detect a compatible project type"

### ISSUE THREAD

**Issue by lashnag** [endroid/installer#2]
I want to use installer in my project "Endroid Installer did not detect a compatible project type". I try to use it even on empty project, but i have the same probrem (i want to use endroid/qr-code, but installer is dependensy for this project).

What i need to do to use it on my project?

Empty project composer json:
`{
    "name": "bla/bla",
    "description": "Test",
    "require": {}
}
`
Composer lock:
`{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
        "This file is @generated automatically"
    ],
    "content-hash": "8d92478768248d4c582a4fe5a83acb4e",
    "packages": [
        {
            "name": "endroid/installer",
            "version": "1.0.5",
            "source": {
                "type": "git",
                "url": "https://github.com/endroid/installer.git",
                "reference": "1472a01e730e5ba37e82bd99694daae92dda0578"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/endroid/installer/zipball/1472a01e730e5ba37e82bd99694daae92dda0578",
                "reference": "1472a01e730e5ba37e82bd99694daae92dda0578",
                "shasum": ""
            },
            "require": {
                "composer-plugin-api": "^1.1",
                "php": ">=7.1"
            },
            "require-dev": {
                "phpunit/phpunit": "^5.7|^6.0"
            },
            "type": "composer-plugin",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.x-dev"
                },
                "class": "Endroid\\Installer\\Installer"
            },
            "autoload": {
                "psr-4": {
                    "Endroid\\Installer\\": "src"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Jeroen van den Enden",
                    "email": "info@endroid.nl"
                }
            ],
            "time": "2018-07-15T08:21:39+00:00"
        }
    ],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": [],
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": []
}
`

**Comment by endroid** [comment]
Hi @lashnag this is not a warning, just a notice. If you have no framework installed the installer doesn't need to do anything. The reason the message is there is that people who intend to use auto configuration should be notified when no compatible project type is detected.

However, I can imagine the message can be interpreted differently so I will see if I can change it to something like "No auto configuration available for this project type".

Thank you!
