### ISSUE TITLE
Prevent installation

### ISSUE THREAD

**Issue by grachevko** [endroid/installer#3]
What if i don't want to commit configuration from your installer directory? 
Every run of `composer install` i see new files, i don't want them. 

Moreover i can't remove endroid/installer because i use endroid/qr-code which require endroid/installer.

**Comment by endroid** [comment]
Hi @grachevko, you can read how to disable installation in the configuration section of the readme https://github.com/endroid/installer/blob/master/README.md#configuration. Please let me know if you experience any issues.
