### ISSUE TITLE
Support PHP config

### ISSUE THREAD

**Issue by stephanvierkant** [endroid/installer#5]
I've changed my yaml files to php configuration files, but Endroid Installer still creates the yaml files. It would be great if Endroid Installer supports PHP configuration files too.

**Comment by endroid** [comment]
Hi @stephanvierkant thank you for your question. The installer is created so it simply copies the contents of the .install/<project-type> directory of a library so it contains either YAML or PHP. In other words: both are "supported" but the library you installed apparently comes with a YAML configuration by default.

I plan to change YAML to PHP configuration files, as they are more flexible, but I will not add an option to choose a preferred configuration type if that is what you mean. If you have your own PHP configuration file and don't want the YAML file to be created you can disable auto-installation in general or for the specific package as described here https://github.com/endroid/installer#configuration.

Hope this helps.
